import type { FastifyPluginAsync } from "fastify";
import { idParams, notFound, pageMeta, paginationQuery, routeSchema } from "../shared/http.js";
import { normalizeSlug } from "../shared/slug.js";
const body = { type: "object", additionalProperties: false, required: ["name", "slug"], properties: { name: { type: "string", minLength: 1, maxLength: 191 }, slug: { type: "string", minLength: 1, maxLength: 191 }, description: { type: "string", maxLength: 10000 }, status: { type: "string", enum: ["DRAFT", "ACTIVE", "ARCHIVED"] } } };

export const categoryRoutes: FastifyPluginAsync = async (app) => {
  app.get("/api/v1/categories", { schema: routeSchema(["Categories"], "List active categories") }, async () => ({ success: true, data: await app.prisma.category.findMany({ where: { status: "ACTIVE" }, select: { id: true, name: true, slug: true, description: true }, orderBy: { name: "asc" } }) }));
  app.get("/api/v1/admin/categories", { schema: routeSchema(["Admin", "Categories"], "List categories for administration", { security: [{ bearerAuth: [] }], querystring: paginationQuery }) }, async (request) => {
    await request.requireAdmin(); const q = request.query as { page?: number; limit?: number; search?: string; status?: "DRAFT" | "ACTIVE" | "ARCHIVED" }; const page = q.page ?? 1, limit = q.limit ?? 20;
    const where = { ...(q.status ? { status: q.status } : {}), ...(q.search ? { name: { contains: q.search } } : {}) };
    const [data, total] = await app.prisma.$transaction([app.prisma.category.findMany({ where, skip: (page - 1) * limit, take: limit, orderBy: { createdAt: "desc" } }), app.prisma.category.count({ where })]);
    return { success: true, data, meta: pageMeta(page, limit, total) };
  });
  app.get("/api/v1/admin/categories/:id", { schema: routeSchema(["Admin", "Categories"], "Get a category", { security: [{ bearerAuth: [] }], params: idParams }) }, async (request) => { await request.requireAdmin(); const item = await app.prisma.category.findUnique({ where: { id: (request.params as { id: string }).id } }); if (!item) throw notFound("Category not found"); return { success: true, data: item }; });
  app.post("/api/v1/admin/categories", { schema: routeSchema(["Admin", "Categories"], "Create a category", { security: [{ bearerAuth: [] }], body }) }, async (request, reply) => { await request.requireAdmin(); const input = request.body as { name: string; slug: string; description?: string; status?: "DRAFT" | "ACTIVE" | "ARCHIVED" }; const item = await app.prisma.category.create({ data: { ...input, name: input.name.trim(), slug: normalizeSlug(input.slug) } }); reply.code(201); return { success: true, data: item }; });
  app.put("/api/v1/admin/categories/:id", { schema: routeSchema(["Admin", "Categories"], "Update a category", { security: [{ bearerAuth: [] }], params: idParams, body: { ...body, required: [], minProperties: 1 } }) }, async (request) => { await request.requireAdmin(); const { id } = request.params as { id: string }; const exists = await app.prisma.category.findUnique({ where: { id } }); if (!exists) throw notFound("Category not found"); const input = request.body as { name?: string; slug?: string; description?: string; status?: "DRAFT" | "ACTIVE" | "ARCHIVED" }; return { success: true, data: await app.prisma.category.update({ where: { id }, data: { ...input, ...(input.name ? { name: input.name.trim() } : {}), ...(input.slug ? { slug: normalizeSlug(input.slug) } : {}) } }) }; });
  app.delete("/api/v1/admin/categories/:id", { schema: routeSchema(["Admin", "Categories"], "Delete a category", { security: [{ bearerAuth: [] }], params: idParams }) }, async (request, reply) => { await request.requireAdmin(); const id = (request.params as { id: string }).id; const category = await app.prisma.category.findUnique({ where: { id }, include: { _count: { select: { products: true } } } }); if (!category) throw notFound("Category not found"); if (category._count.products) throw Object.assign(new Error("Categories with products cannot be deleted"), { statusCode: 409, code: "CATEGORY_IN_USE" }); await app.prisma.category.delete({ where: { id } }); reply.code(204).send(); });
};
