import type { FastifyPluginAsync } from "fastify";
import { idParams, notFound, pageMeta, routeSchema } from "../shared/http.js";
const pageBody = { type: "object", additionalProperties: false, required: ["title", "slug"], properties: { title: { type: "string", minLength: 1, maxLength: 191 }, slug: { type: "string", minLength: 1, maxLength: 191 }, seoTitle: { type: "string", maxLength: 191 }, seoDescription: { type: "string", maxLength: 500 }, sections: { type: "array", items: { type: "object", additionalProperties: false, required: ["type", "content"], properties: { type: { type: "string", maxLength: 100 }, content: { type: "object" }, position: { type: "integer", minimum: 0 } } } } } };
const bannerBody = { type: "object", additionalProperties: false, required: ["title", "imageUrl"], properties: { title: { type: "string", minLength: 1, maxLength: 191 }, imageUrl: { type: "string", format: "uri" }, mobileImageUrl: { type: "string", format: "uri" }, linkUrl: { type: "string", format: "uri" }, altText: { type: "string", maxLength: 500 }, status: { type: "string", enum: ["DRAFT", "ACTIVE", "ARCHIVED"] }, position: { type: "integer", minimum: 0 }, pageId: { type: "string" }, startAt: { type: "string", format: "date-time" }, endAt: { type: "string", format: "date-time" } } };
const pageInclude = { sections: { orderBy: { position: "asc" as const } }, banners: { where: { status: "ACTIVE" as const }, orderBy: { position: "asc" as const } } };
function pageData(input: any) { const { sections, ...data } = input; return { ...data, ...(sections ? { sections: { create: sections } } : {}) }; }

export const cmsRoutes: FastifyPluginAsync = async (app) => {
  app.get("/api/v1/cms/home", { schema: routeSchema(["CMS"], "Get the published home page") }, async () => { const page = await app.prisma.cmsPage.findFirst({ where: { slug: "home", status: "PUBLISHED" }, include: pageInclude }); if (!page) throw notFound("Home page not found"); return { success: true, data: page }; });
  app.get("/api/v1/cms/pages/:slug", { schema: routeSchema(["CMS"], "Get a published page", { params: { type: "object", required: ["slug"], properties: { slug: { type: "string" } } } }) }, async (request) => { const page = await app.prisma.cmsPage.findFirst({ where: { slug: (request.params as any).slug, status: "PUBLISHED" }, include: pageInclude }); if (!page) throw notFound("Page not found"); return { success: true, data: page }; });
  app.get("/api/v1/cms/banners", { schema: routeSchema(["CMS"], "List active banners") }, async () => ({ success: true, data: await app.prisma.banner.findMany({ where: { status: "ACTIVE", AND: [{ OR: [{ startAt: null }, { startAt: { lte: new Date() } }] }, { OR: [{ endAt: null }, { endAt: { gte: new Date() } }] }] }, orderBy: { position: "asc" } }) }));
  app.get("/api/v1/admin/cms/pages", { schema: routeSchema(["Admin", "CMS"], "List CMS pages", { security: [{ bearerAuth: [] }], querystring: { type: "object", properties: { page: { type: "integer", minimum: 1, default: 1 }, limit: { type: "integer", minimum: 1, maximum: 100, default: 20 } } } }) }, async (request) => { await request.requireAdmin(); const q = request.query as any, page = q.page ?? 1, limit = q.limit ?? 20; const [data, total] = await app.prisma.$transaction([app.prisma.cmsPage.findMany({ include: { sections: true }, skip: (page - 1) * limit, take: limit, orderBy: { updatedAt: "desc" } }), app.prisma.cmsPage.count()]); return { success: true, data, meta: pageMeta(page, limit, total) }; });
  app.get("/api/v1/admin/cms/pages/:id", { schema: routeSchema(["Admin", "CMS"], "Get a CMS page", { security: [{ bearerAuth: [] }], params: idParams }) }, async (request) => { await request.requireAdmin(); const page = await app.prisma.cmsPage.findUnique({ where: { id: (request.params as any).id }, include: { sections: { orderBy: { position: "asc" } }, banners: true } }); if (!page) throw notFound("Page not found"); return { success: true, data: page }; });
  app.post("/api/v1/admin/cms/pages", { schema: routeSchema(["Admin", "CMS"], "Create a CMS page", { security: [{ bearerAuth: [] }], body: pageBody }) }, async (request, reply) => { await request.requireAdmin(); const page = await app.prisma.cmsPage.create({ data: pageData(request.body as any), include: { sections: true } }); reply.code(201); return { success: true, data: page }; });
  app.put("/api/v1/admin/cms/pages/:id", { schema: routeSchema(["Admin", "CMS"], "Update a CMS page", { security: [{ bearerAuth: [] }], params: idParams, body: { ...pageBody, required: [], minProperties: 1 } }) }, async (request) => { await request.requireAdmin(); const id = (request.params as any).id, input = request.body as any; if (!(await app.prisma.cmsPage.findUnique({ where: { id } }))) throw notFound("Page not found"); const { sections, ...data } = input; const page = await app.prisma.cmsPage.update({ where: { id }, data: { ...data, ...(sections ? { sections: { deleteMany: {}, create: sections } } : {}) }, include: { sections: { orderBy: { position: "asc" } } } }); return { success: true, data: page }; });
  app.delete("/api/v1/admin/cms/pages/:id", { schema: routeSchema(["Admin", "CMS"], "Delete a CMS page", { security: [{ bearerAuth: [] }], params: idParams }) }, async (request, reply) => { await request.requireAdmin(); const id = (request.params as any).id; if (!(await app.prisma.cmsPage.findUnique({ where: { id } }))) throw notFound("Page not found"); await app.prisma.cmsPage.delete({ where: { id } }); reply.code(204).send(); });
  app.post("/api/v1/admin/cms/pages/:id/publish", { schema: routeSchema(["Admin", "CMS"], "Publish a CMS page", { security: [{ bearerAuth: [] }], params: idParams }) }, async (request) => { await request.requireAdmin(); const id = (request.params as any).id; if (!(await app.prisma.cmsPage.findUnique({ where: { id } }))) throw notFound("Page not found"); return { success: true, data: await app.prisma.cmsPage.update({ where: { id }, data: { status: "PUBLISHED", publishedAt: new Date(), unpublishedAt: null } }) }; });
  app.post("/api/v1/admin/cms/pages/:id/unpublish", { schema: routeSchema(["Admin", "CMS"], "Unpublish a CMS page", { security: [{ bearerAuth: [] }], params: idParams }) }, async (request) => { await request.requireAdmin(); const id = (request.params as any).id; if (!(await app.prisma.cmsPage.findUnique({ where: { id } }))) throw notFound("Page not found"); return { success: true, data: await app.prisma.cmsPage.update({ where: { id }, data: { status: "DRAFT", unpublishedAt: new Date() } }) }; });
  app.get("/api/v1/admin/cms/banners", { schema: routeSchema(["Admin", "CMS"], "List banners", { security: [{ bearerAuth: [] }] }) }, async (request) => { await request.requireAdmin(); return { success: true, data: await app.prisma.banner.findMany({ orderBy: { position: "asc" } }) }; });
  app.get("/api/v1/admin/cms/banners/:id", { schema: routeSchema(["Admin", "CMS"], "Get a banner", { security: [{ bearerAuth: [] }], params: idParams }) }, async (request) => { await request.requireAdmin(); const banner = await app.prisma.banner.findUnique({ where: { id: (request.params as { id: string }).id } }); if (!banner) throw notFound("Banner not found"); return { success: true, data: banner }; });
  app.post("/api/v1/admin/cms/banners", { schema: routeSchema(["Admin", "CMS"], "Create a banner", { security: [{ bearerAuth: [] }], body: bannerBody }) }, async (request, reply) => { await request.requireAdmin(); const item = await app.prisma.banner.create({ data: request.body as any }); reply.code(201); return { success: true, data: item }; });
  app.put("/api/v1/admin/cms/banners/:id", { schema: routeSchema(["Admin", "CMS"], "Update a banner", { security: [{ bearerAuth: [] }], params: idParams, body: { ...bannerBody, required: [], minProperties: 1 } }) }, async (request) => { await request.requireAdmin(); const id = (request.params as any).id; if (!(await app.prisma.banner.findUnique({ where: { id } }))) throw notFound("Banner not found"); return { success: true, data: await app.prisma.banner.update({ where: { id }, data: request.body as any }) }; });
  app.delete("/api/v1/admin/cms/banners/:id", { schema: routeSchema(["Admin", "CMS"], "Delete a CMS banner", { security: [{ bearerAuth: [] }], params: idParams }) }, async (request, reply) => { await request.requireAdmin(); const id = (request.params as any).id; if (!(await app.prisma.banner.findUnique({ where: { id } }))) throw notFound("Banner not found"); await app.prisma.banner.delete({ where: { id } }); reply.code(204).send(); });
};
