import { createHash } from "node:crypto";
import type { FastifyPluginAsync } from "fastify";
import { idParams, notFound, pageMeta, routeSchema } from "../shared.js";
const body = { type: "object", required: ["url", "filename", "mimeType"], properties: { url: { type: "string", format: "uri" }, filename: { type: "string", maxLength: 500 }, altText: { type: "string", maxLength: 500 }, mimeType: { type: "string", maxLength: 191 }, metadata: { type: "object" } } };
const hashUrl = (url: string) => createHash("sha256").update(url).digest("hex");
export const mediaRoutes: FastifyPluginAsync = async (app) => {
  app.get("/api/v1/admin/media", { schema: routeSchema(["Admin", "Media"], "List media metadata", { security: [{ bearerAuth: [] }] }) }, async (request) => { await request.requireAdmin(); const data = await app.prisma.media.findMany({ orderBy: { createdAt: "desc" }, take: 100 }); return { success: true, data, meta: pageMeta(1, 100, data.length) }; });
  app.get("/api/v1/admin/media/:id", { schema: routeSchema(["Admin", "Media"], "Get media metadata", { security: [{ bearerAuth: [] }], params: idParams }) }, async (request) => { await request.requireAdmin(); const media = await app.prisma.media.findUnique({ where: { id: (request.params as { id: string }).id } }); if (!media) throw notFound("Media not found"); return { success: true, data: media }; });
  app.post("/api/v1/admin/media", { schema: routeSchema(["Admin", "Media"], "Register externally stored media", { security: [{ bearerAuth: [] }], body }) }, async (request, reply) => { await request.requireAdmin(); const data = request.body as any; const media = await app.prisma.media.create({ data: { ...data, urlHash: hashUrl(data.url) } }); reply.code(201); return { success: true, data: media }; });
  app.put("/api/v1/admin/media/:id", { schema: routeSchema(["Admin", "Media"], "Update media metadata", { security: [{ bearerAuth: [] }], params: idParams, body: { ...body, required: [] } }) }, async (request) => { await request.requireAdmin(); const id = (request.params as { id: string }).id; if (!(await app.prisma.media.findUnique({ where: { id } }))) throw notFound("Media not found"); const data = request.body as any; return { success: true, data: await app.prisma.media.update({ where: { id }, data: { ...data, ...(data.url ? { urlHash: hashUrl(data.url) } : {}) } }) }; });
  app.delete("/api/v1/admin/media/:id", { schema: routeSchema(["Admin", "Media"], "Delete media metadata", { security: [{ bearerAuth: [] }], params: idParams }) }, async (request, reply) => { await request.requireAdmin(); const id = (request.params as { id: string }).id; if (!(await app.prisma.media.findUnique({ where: { id } }))) throw notFound("Media not found"); await app.prisma.media.delete({ where: { id } }); reply.code(204).send(); });
};
