import type { FastifyPluginAsync } from "fastify";
import { idParams, notFound, pageMeta, paginationQuery, routeSchema } from "../shared/http.js";
import { normalizeSlug } from "../shared/slug.js";
import { mediaPath } from "../shared/media.js";
import { compareAtPriceViolation, PUBLIC_VARIANT_FILTER } from "../shared/product-rules.js";
// Storefront tab content: short bullet lists (Description tab).
const listOfText = { type: "array", maxItems: 30, items: { type: "string", minLength: 1, maxLength: 300 } };
const productBody = { type: "object", additionalProperties: false, required: ["name", "slug", "price", "categoryId"], properties: { name: { type: "string", minLength: 1, maxLength: 191 }, slug: { type: "string", minLength: 1, maxLength: 191 }, description: { type: "string", maxLength: 50000 }, features: listOfText, materials: listOfText, specifications: { type: "array", maxItems: 50, items: { type: "object", additionalProperties: false, required: ["label", "value"], properties: { label: { type: "string", minLength: 1, maxLength: 100 }, value: { type: "string", minLength: 1, maxLength: 500 } } } }, returnPolicy: { type: "string", maxLength: 5000 }, warranty: { type: "string", maxLength: 5000 }, price: { type: "number", minimum: 0 }, compareAtPrice: { type: "number", minimum: 0 }, sku: { type: "string", maxLength: 191 }, status: { type: "string", enum: ["DRAFT", "ACTIVE", "ARCHIVED"] }, categoryId: { type: "string", minLength: 1 }, quantity: { type: "integer", minimum: 0 }, images: { type: "array", maxItems: 20, items: { type: "object", additionalProperties: false, required: ["mediaId"], properties: { mediaId: { type: "string", minLength: 1 }, altText: { type: "string", maxLength: 500 }, position: { type: "integer", minimum: 0 }, isPrimary: { type: "boolean" } } } }, variants: { type: "array", items: { type: "object", additionalProperties: false, required: ["name", "sku", "options"], properties: { name: { type: "string" }, sku: { type: "string" }, price: { type: "number", minimum: 0 }, options: { type: "object" }, status: { type: "string", enum: ["DRAFT", "ACTIVE", "ARCHIVED"] } } } } } };
const include = { category: { select: { id: true, name: true, slug: true } }, images: { orderBy: { position: "asc" as const } }, variants: true, inventory: true };
// Storefront responses: same shape, but DRAFT/ARCHIVED variants are left out.
const publicInclude = { ...include, variants: PUBLIC_VARIANT_FILTER };
// An empty return policy or warranty is stored as NULL, which the storefront shows as the store-wide default.
function policyText(input: any) { return { ...(input.returnPolicy !== undefined ? { returnPolicy: input.returnPolicy.trim() || null } : {}), ...(input.warranty !== undefined ? { warranty: input.warranty.trim() || null } : {}) }; }
function writeData(input: any) { const { images, variants, quantity, ...data } = input; return { ...data, ...policyText(input), ...(images ? { images: { create: images } } : {}), ...(variants ? { variants: { create: variants } } : {}), ...(quantity !== undefined ? { inventory: { create: { quantity } } } : {}) }; }

// Every product response carries a usable `url` per image: uploaded images point at this API's
// media endpoint (derived from mediaId, never stored); legacy rows keep their stored URL.
type WithImages = { images: { mediaId: string | null; url: string | null }[] };
function present<T extends WithImages>(product: T): T {
  return { ...product, images: product.images.map((image) => ({ ...image, url: image.mediaId ? mediaPath(image.mediaId) : image.url })) };
}

export const productRoutes: FastifyPluginAsync = async (app) => {
  // Images may only reference media that were uploaded to this API (they have stored bytes).
  async function assertUploadedMedia(images: { mediaId: string }[] | undefined) {
    if (!images?.length) return;
    const ids = [...new Set(images.map((image) => image.mediaId))];
    const found = await app.prisma.media.count({ where: { id: { in: ids }, size: { not: null } } });
    if (found !== ids.length) throw notFound("Media not found");
  }

  // Uploaded images belong to the product that shows them: once no product image references
  // them (images replaced, product deleted), their stored bytes are removed.
  async function mediaIdsOf(productId: string) {
    const rows = await app.prisma.productImage.findMany({ where: { productId, mediaId: { not: null } }, select: { mediaId: true } });
    return rows.map((row) => row.mediaId!);
  }
  async function pruneUnusedMedia(ids: string[]) {
    if (ids.length) await app.prisma.media.deleteMany({ where: { id: { in: ids }, size: { not: null }, productImages: { none: {} } } });
  }

  app.get("/api/v1/products", { schema: routeSchema(["Products"], "List active products", { querystring: paginationQuery }) }, async (request) => { const q = request.query as any, page = q.page ?? 1, limit = q.limit ?? 20; const where = { status: "ACTIVE" as const, ...(q.categoryId ? { categoryId: q.categoryId } : {}), ...(q.search ? { OR: [{ name: { contains: q.search } }, { slug: { contains: q.search } }] } : {}) }; const [data, total] = await app.prisma.$transaction([app.prisma.product.findMany({ where, include: publicInclude, skip: (page - 1) * limit, take: limit, orderBy: { createdAt: "desc" } }), app.prisma.product.count({ where })]); return { success: true, data: data.map(present), meta: pageMeta(page, limit, total) }; });
  app.get("/api/v1/products/:slug", { schema: routeSchema(["Products"], "Get an active product by slug", { params: { type: "object", required: ["slug"], properties: { slug: { type: "string" } } } }) }, async (request) => { const item = await app.prisma.product.findFirst({ where: { slug: (request.params as any).slug, status: "ACTIVE" }, include: publicInclude }); if (!item) throw notFound("Product not found"); return { success: true, data: present(item) }; });
  app.get("/api/v1/admin/products", { schema: routeSchema(["Admin", "Products"], "List products for administration", { security: [{ bearerAuth: [] }], querystring: paginationQuery }) }, async (request) => { await request.requireAdmin(); const q = request.query as any, page = q.page ?? 1, limit = q.limit ?? 20; const where = { ...(q.status ? { status: q.status } : {}), ...(q.categoryId ? { categoryId: q.categoryId } : {}), ...(q.search ? { OR: [{ name: { contains: q.search } }, { sku: { contains: q.search } }] } : {}) }; const [data, total] = await app.prisma.$transaction([app.prisma.product.findMany({ where, include, skip: (page - 1) * limit, take: limit, orderBy: { createdAt: "desc" } }), app.prisma.product.count({ where })]); return { success: true, data: data.map(present), meta: pageMeta(page, limit, total) }; });
  app.get("/api/v1/admin/products/:id", { schema: routeSchema(["Admin", "Products"], "Get a product", { security: [{ bearerAuth: [] }], params: idParams }) }, async (request) => { await request.requireAdmin(); const item = await app.prisma.product.findUnique({ where: { id: (request.params as any).id }, include }); if (!item) throw notFound("Product not found"); return { success: true, data: present(item) }; });
  app.post("/api/v1/admin/products", { schema: routeSchema(["Admin", "Products"], "Create a product", { security: [{ bearerAuth: [] }], body: productBody }) }, async (request, reply) => { await request.requireAdmin(); const input = request.body as any; if (compareAtPriceViolation(input.price, input.compareAtPrice)) throw Object.assign(new Error("compareAtPrice must be greater than or equal to price"), { statusCode: 400, code: "VALIDATION_ERROR" }); if (!(await app.prisma.category.findUnique({ where: { id: input.categoryId } }))) throw notFound("Category not found"); await assertUploadedMedia(input.images); const item = await app.prisma.product.create({ data: writeData({ ...input, name: input.name.trim(), slug: normalizeSlug(input.slug) }), include }); reply.code(201); return { success: true, data: present(item) }; });
  app.put("/api/v1/admin/products/:id", { schema: routeSchema(["Admin", "Products"], "Update a product", { security: [{ bearerAuth: [] }], params: idParams, body: { ...productBody, required: [], minProperties: 1 } }) }, async (request) => { await request.requireAdmin(); const id = (request.params as any).id, input = request.body as any; const existing = await app.prisma.product.findUnique({ where: { id }, select: { price: true, compareAtPrice: true } }); if (!existing) throw notFound("Product not found"); const { images, variants, quantity, ...data } = input; if (compareAtPriceViolation(input.price ?? Number(existing.price), input.compareAtPrice !== undefined ? input.compareAtPrice : existing.compareAtPrice === null ? null : Number(existing.compareAtPrice))) throw Object.assign(new Error("compareAtPrice must be greater than or equal to price"), { statusCode: 400, code: "VALIDATION_ERROR" }); if (input.categoryId && !(await app.prisma.category.findUnique({ where: { id: input.categoryId } }))) throw notFound("Category not found"); await assertUploadedMedia(images); const previousMedia = images ? await mediaIdsOf(id) : []; const item = await app.prisma.product.update({ where: { id }, data: { ...data, ...policyText(input), ...(input.name ? { name: input.name.trim() } : {}), ...(input.slug ? { slug: normalizeSlug(input.slug) } : {}), ...(quantity !== undefined ? { inventory: { upsert: { create: { quantity }, update: { quantity } } } } : {}), ...(images ? { images: { deleteMany: {}, create: images } } : {}), ...(variants ? { variants: { deleteMany: {}, create: variants } } : {}) }, include }); await pruneUnusedMedia(previousMedia); return { success: true, data: present(item) }; });
  app.delete("/api/v1/admin/products/:id", { schema: routeSchema(["Admin", "Products"], "Delete a product", { security: [{ bearerAuth: [] }], params: idParams }) }, async (request, reply) => { await request.requireAdmin(); const id = (request.params as any).id; if (!(await app.prisma.product.findUnique({ where: { id } }))) throw notFound("Product not found"); const previousMedia = await mediaIdsOf(id); await app.prisma.product.delete({ where: { id } }); await pruneUnusedMedia(previousMedia); reply.code(204).send(); });
};
