import type { FastifyPluginAsync } from "fastify";
import { idParams, notFound, pageMeta, paginationQuery, routeSchema } from "../shared.js";
import { normalizeSlug } from "../../shared/slug.js";
const productBody = { type: "object", additionalProperties: false, required: ["name", "slug", "price", "categoryId"], properties: { name: { type: "string", minLength: 1, maxLength: 191 }, slug: { type: "string", minLength: 1, maxLength: 191 }, description: { type: "string", maxLength: 50000 }, price: { type: "number", minimum: 0 }, compareAtPrice: { type: "number", minimum: 0 }, sku: { type: "string", maxLength: 191 }, status: { type: "string", enum: ["DRAFT", "ACTIVE", "ARCHIVED"] }, categoryId: { type: "string", minLength: 1 }, quantity: { type: "integer", minimum: 0 }, images: { type: "array", items: { type: "object", additionalProperties: false, required: ["url"], properties: { url: { type: "string", format: "uri" }, altText: { type: "string", maxLength: 500 }, position: { type: "integer", minimum: 0 }, isPrimary: { type: "boolean" } } } }, variants: { type: "array", items: { type: "object", additionalProperties: false, required: ["name", "sku", "options"], properties: { name: { type: "string" }, sku: { type: "string" }, price: { type: "number", minimum: 0 }, options: { type: "object" }, status: { type: "string", enum: ["DRAFT", "ACTIVE", "ARCHIVED"] } } } } } };
const include = { category: { select: { id: true, name: true, slug: true } }, images: { orderBy: { position: "asc" as const } }, variants: true, inventory: true };
function writeData(input: any) { const { images, variants, quantity, ...data } = input; return { ...data, ...(images ? { images: { create: images } } : {}), ...(variants ? { variants: { create: variants } } : {}), ...(quantity !== undefined ? { inventory: { create: { quantity } } } : {}) }; }

export const productRoutes: FastifyPluginAsync = async (app) => {
  app.get("/api/v1/products", { schema: routeSchema(["Products"], "List active products", { querystring: paginationQuery }) }, async (request) => { const q = request.query as any, page = q.page ?? 1, limit = q.limit ?? 20; const where = { status: "ACTIVE" as const, ...(q.categoryId ? { categoryId: q.categoryId } : {}), ...(q.search ? { OR: [{ name: { contains: q.search } }, { slug: { contains: q.search } }] } : {}) }; const [data, total] = await app.prisma.$transaction([app.prisma.product.findMany({ where, include, skip: (page - 1) * limit, take: limit, orderBy: { createdAt: "desc" } }), app.prisma.product.count({ where })]); return { success: true, data, meta: pageMeta(page, limit, total) }; });
  app.get("/api/v1/products/:slug", { schema: routeSchema(["Products"], "Get an active product by slug", { params: { type: "object", required: ["slug"], properties: { slug: { type: "string" } } } }) }, async (request) => { const item = await app.prisma.product.findFirst({ where: { slug: (request.params as any).slug, status: "ACTIVE" }, include }); if (!item) throw notFound("Product not found"); return { success: true, data: item }; });
  app.get("/api/v1/admin/products", { schema: routeSchema(["Admin", "Products"], "List products for administration", { security: [{ bearerAuth: [] }], querystring: paginationQuery }) }, async (request) => { await request.requireAdmin(); const q = request.query as any, page = q.page ?? 1, limit = q.limit ?? 20; const where = { ...(q.status ? { status: q.status } : {}), ...(q.categoryId ? { categoryId: q.categoryId } : {}), ...(q.search ? { OR: [{ name: { contains: q.search } }, { sku: { contains: q.search } }] } : {}) }; const [data, total] = await app.prisma.$transaction([app.prisma.product.findMany({ where, include, skip: (page - 1) * limit, take: limit, orderBy: { createdAt: "desc" } }), app.prisma.product.count({ where })]); return { success: true, data, meta: pageMeta(page, limit, total) }; });
  app.get("/api/v1/admin/products/:id", { schema: routeSchema(["Admin", "Products"], "Get a product", { security: [{ bearerAuth: [] }], params: idParams }) }, async (request) => { await request.requireAdmin(); const item = await app.prisma.product.findUnique({ where: { id: (request.params as any).id }, include }); if (!item) throw notFound("Product not found"); return { success: true, data: item }; });
  app.post("/api/v1/admin/products", { schema: routeSchema(["Admin", "Products"], "Create a product", { security: [{ bearerAuth: [] }], body: productBody }) }, async (request, reply) => { await request.requireAdmin(); const input = request.body as any; if (input.compareAtPrice !== undefined && input.compareAtPrice < input.price) throw Object.assign(new Error("compareAtPrice must be greater than or equal to price"), { statusCode: 400, code: "VALIDATION_ERROR" }); if (!(await app.prisma.category.findUnique({ where: { id: input.categoryId } }))) throw notFound("Category not found"); const item = await app.prisma.product.create({ data: writeData({ ...input, name: input.name.trim(), slug: normalizeSlug(input.slug) }), include }); reply.code(201); return { success: true, data: item }; });
  app.put("/api/v1/admin/products/:id", { schema: routeSchema(["Admin", "Products"], "Update a product", { security: [{ bearerAuth: [] }], params: idParams, body: { ...productBody, required: [], minProperties: 1 } }) }, async (request) => { await request.requireAdmin(); const id = (request.params as any).id, input = request.body as any; if (!(await app.prisma.product.findUnique({ where: { id } }))) throw notFound("Product not found"); const { images, variants, quantity, ...data } = input; if (input.compareAtPrice !== undefined && input.price !== undefined && input.compareAtPrice < input.price) throw Object.assign(new Error("compareAtPrice must be greater than or equal to price"), { statusCode: 400, code: "VALIDATION_ERROR" }); if (input.categoryId && !(await app.prisma.category.findUnique({ where: { id: input.categoryId } }))) throw notFound("Category not found"); const item = await app.prisma.product.update({ where: { id }, data: { ...data, ...(input.name ? { name: input.name.trim() } : {}), ...(input.slug ? { slug: normalizeSlug(input.slug) } : {}), ...(quantity !== undefined ? { inventory: { upsert: { create: { quantity }, update: { quantity } } } } : {}), ...(images ? { images: { deleteMany: {}, create: images } } : {}), ...(variants ? { variants: { deleteMany: {}, create: variants } } : {}) }, include }); return { success: true, data: item }; });
  app.delete("/api/v1/admin/products/:id", { schema: routeSchema(["Admin", "Products"], "Delete a product", { security: [{ bearerAuth: [] }], params: idParams }) }, async (request, reply) => { await request.requireAdmin(); const id = (request.params as any).id; if (!(await app.prisma.product.findUnique({ where: { id } }))) throw notFound("Product not found"); await app.prisma.product.delete({ where: { id } }); reply.code(204).send(); });
};
